### ISSUE TITLE
ST.FeaturePlot: How to change indices numbers to section names

### ISSUE THREAD

**Issue by nmatigian** [jbergenstrahle/STUtility#13]
ST.FeaturePlot(object = se, features = "seurat_clusters", indices = 1:9, ncol = 3, pt.border = F,cols = mycolors)

The above code each section is labeled 1:9, but would like to use the names in se$section (created as # Add a section column to your meta.data in the norm Tutorial)

**Comment by ludvigla** [comment]
Unfortunately, this option is not yet implemented in `ST.FeaturePlot`. You could create 9 separate plots and then arrange them into one plot. However, this will cause the subplots to have different color scales.

**Comment by NyKepler** [comment]
label.by = "section"
