### ISSUE TITLE
Coordinates for deconvolution

### ISSUE THREAD

**Issue by oligomyeggo** [jbergenstrahle/STUtility#15]
Hello, thank you for your excellent tool! I have really enjoyed using STUtility to analyze my spatial data thus far. I have a question about the `meta.data` stored in the `Staffli` object, and I want to make sure I am grabbing the correct values for deconvolution analysis. Can you please tell me the difference between `x, y`, `adj_x, adj_y`, `pixel_x, pixel_y`, and `warped_x, warped_y`? Which would be the most correct pair of values to represent the x and y coordinates of the barcodes? I am guessing `x, y` are the original coordinates before any imaging processing is done, and `warped_x, warped_y` correspond to to the coordinates after rotating (or warping) the image?

**Comment by ludvigla** [comment]
Hi there,

The `x, y` coordinates represents the positions within the capture area spot grid. These coordinates are not very useful if you want to map the spots on the H&E image for example, but can be used when an H&E image is not provided. The `adj_x, adj_y` are essentially the same thing, but is a remnant from earlier versions of the capture arrays (we call them 1k and 2k arrays). The printing of spots is not perfect, in particular for previous array versions, so we used a tool called the ST spot detector to correct the positions. If you analyze Visium data, these coordinates are redundant. 
The `pixel_x, pixel_y` coordinates are the ones you use to map spots on the H&E image. However, there's usually some scaling factor required depending on the resolution of the H&E image. `warped_x, warped_y` are the warped `pixel_x, pixel_y` coordinates and should be used when mapping spots on processed H&E images.

**Comment by oligomyeggo** [comment]
Awesome, thank you so much @ludvigla for clarifying all of that. I appreciate it.
