### ISSUE TITLE
R crashes when running STUtility

### ISSUE THREAD

**Issue by aerickso** [jbergenstrahle/STUtility#17]
Hi!

After loading in a seurat object (as .obj), I attempt to inspect the object in the environment by clicking on the Seurat object. The console prompts a message stating that "STUtility is required", which immediately then leads to a R error message.

I completely uninstalled R/RStudio and all libraries, I reinstalled STUtility, and have the same issue.

RStudio
2022.02.2 Build 485

R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

**Comment by ludvigla** [comment]
Hi Andrew,

Could you please share the complete session info and a reproducible example?

**Comment by ludvigla** [comment]
Closing this issue.
