### ISSUE TITLE
Error installing STUtility on HPC - CentOS Linux 7

### ISSUE THREAD

**Issue by alikhuseynov** [jbergenstrahle/STUtility#2]
Hello guys,
Great package and very cool visualizations, very useful for ST data analysis. 
I'm having an issue installing it on HPC - CentOS Linux 7. It runs perfectly on local MacBook Pro Mojave. Any suggestions? Many Thanks!
Alik 

Here is report:
##### note: SingleCellExperiment is installed via BiocManager::install()
> devtools::install_github("jbergenstrahle/STUtility")
Downloading GitHub repo jbergenstrahle/STUtility@master
Skipping 1 packages not available: SingleCellExperiment
   checking for file ‘/general/ephemeral/user/user.name/ephemeral/RtmpfJm9fJ/remotes32231f133b15/jbergenstrahle-STUtility-79138a2/DE
✔  checking for file ‘/general/ephemeral/user/user.name/ephemeral/RtmpfJm9fJ/remotes32231f133b15/jbergenstrahle-STUtility-79138a2/DESCRIPTION’ (670ms)
─  preparing ‘STutility’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘STutility_0.1.0.tar.gz’
   Warnung: invalid uid value replaced by that for user 'nobody'
   Warnung: invalid gid value replaced by that for user 'nobody'
>* installing *source* package ‘STutility’ ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
fehlende Dateien im 'Collate' Feld von '/general/ephemeral/user/user.name/ephemeral/RtmpQPKF4o/R.INSTALL47804ef27432/STutility/R':
  CMYK.R
ERROR: unable to collate and parse R files for package ‘STutility’

##### session info
>R version 3.6.3 (2020-02-29)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
Matrix products: default
BLAS/LAPACK: /rdsgpfs/general/user/ahuseyno/home/anaconda3/envs/scanpy/lib/libopenblasp-r0.3.7.so
locale:
 [1] LC_CTYPE=de_CH.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=de_CH.UTF-8    
 [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=de_CH.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by ludvigla** [comment]
Hi there @alikhuseynov! I hope you managed to install the package, but the issue should've been resolved by now in the latest version.
