### ISSUE TITLE
Create a STutility.Object from a Seurat.Object

### ISSUE THREAD

**Issue by EddieLv** [jbergenstrahle/STUtility#23]
What a great tool for spatial visualization, but I have to create a Seurat.Object for analyzing because of technology limit(which is not 10X Visium), so I wonder if you can support how to create a STutility.Object directly from a created Seurat.Object. Thanks a lot!

**Comment by ludvigla** [comment]
STUtility only supports early versions of ST (1k and 2k arrays) and 10x Visium. It might be possible to make it compatible anyways but you would have to use `CreateStaffliObject()` to customize the spatial data stored in the Seurat object. If you have a Seurat object:

`se <- CreateSeuratObject(...)`

you can then create a `Staffli` object with you spatial data:

`st_object <- CreateStaffliObject(...)`

and then place it in the correct slot inside the `Seurat`object:

`se@tools$Stalli <- st_object`

**Comment by EddieLv** [comment]
Thanks a lot!
