### ISSUE TITLE
Accidental introduction of image artifacts

### ISSUE THREAD

**Issue by FPGro** [jbergenstrahle/STUtility#26]
Hi there,
first of all: thank you for creating and maintaining this package!

Now, I stumbled upon a curious bug: You introduced the ability to Warp images using, well, for example:
`se = WarpImages(se, verbose = T, transforms = list("1" = list(angle = 90)))`
Which accomodates the case that images have not been masked before. This is generally very helpful, but upon trying it out with and without masking I noticed that the lline seems to introduce severe image artifacts for unmasked images (but not for masked images). 
Examples:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/38361879/212074559-9f085291-4be4-487b-9f83-3e67be95e78b.png">

turned into (using the code above)
<img width="193" alt="image" src="https://user-images.githubusercontent.com/38361879/212074503-342007b8-173d-4d99-8a64-7246650e13b7.png">

After digging through the code for a while, I think I pinned the issue to the following lines:

https://github.com/jbergenstrahle/STUtility/blob/9a1b3f1d2ef15714dea1fc6226dc1dfcdd666c29/R/image_processing_utilities.R#L214-L216

which I assume are supposed to replace the brightest (aka closest to white) color in the image with white, presumably to remove artifacts in the background of masked images. When the images are not masked however (or rather, only a dummy mask which is all positive is used), the code may replace one of the slide background colors with white. Upon commenting out those lines, I get the result I expected:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/38361879/212075483-7e0ac5e0-8be2-4d5d-ab57-6b2d71e05a5b.png">

I guess the code makes sense for when the tissue is actually masked. It may make sense to check for that, or alternatively do a sanity check that only near-white pixels can be turned to true white or I guess to just introduce a parameter somewhere to disable this post-processing if necessary. 

Anyways, good luck to you and have a nice day!

**Comment by ludvigla** [comment]
Thanks for pointing this out! If you want to try our new R package `semla`, this should no longer be an issue.

https://github.com/ludvigla/semla

/Ludvig
