### ISSUE TITLE
scaling for technical replicates

### ISSUE THREAD

**Issue by likejie** [jbergenstrahle/STUtility#4]
Hi folks,
Extremely great work! I am able to follow you tutorial and applied to the dataset generated in house.
I have a question dealing with the technical replicates for Visium dataset. In my case, there are 4 technical replicates, i spread them out to different chips and different capture areas. The goal is to exam the variance across chips/capture areas. I can align them well (with a little manual flipping). 3 out of the 4 showed similar sizes, while sample 4 is obviously larger than the rest.
I am wondering from your experience, is there any way to scale the sample 4 to the same as the other 3 samples? (see below the top slice is way bigger than the others)

![image](https://user-images.githubusercontent.com/1277932/96326308-8821ef80-0ffd-11eb-8ce9-86e666476cba.png)

other views

![image](https://user-images.githubusercontent.com/1277932/96326322-b1428000-0ffd-11eb-9538-13c6c16c818a.png)
![image](https://user-images.githubusercontent.com/1277932/96326342-cfa87b80-0ffd-11eb-9f6b-64d25ef2b6c0.png)

Thanks so much!
Best,
-Kejie

**Comment by ludvigla** [comment]
Hi Kejie,

As you have noticed, we haven't implemented any option to scale the images. The only thing you can do is to apply rigid transformations. 

But my suspicion is that the size of the input HE images differ? In that case you could try to crop your images using the `CropImages()` function. You just have to specify a crop window for each section and that way you could probably adjust the sizes as you want.

Another solution would be to crop the images before you run spaceranger and make sure that the tissue sections take up about the same fraction of the images.

Cheers,
Ludvig
