### ISSUE TITLE
Registration to Allen Brain Atlas

### ISSUE THREAD

**Issue by quanc1989** [jbergenstrahle/STUtility#5]
Hi, great work!

I wonder if I can use the automatic alignment method to map coordinates (H&E staining images from mouse brain) to a reference image from Allen Brain Atlas. Then I could segment these spots to annotated brain sections.

Thanks a lot!

**Comment by ludvigla** [comment]
Hi there @quanc1989!

We do not provide an automatic alignment method to map coordinates onto the Allen Brain Atlas. However, this can be done  using the [wholebrain](https://github.com/tractatus/wholebrain) R package created by Daniel Furth. The wholebrain workflow is semi-supervised but we have been able to register H&E images to the anatomical reference atlas (mouse brain) to segment out spots for different anatomical regions.

**Comment by quanc1989** [comment]
Hi @ludvigla 

I have tried wholebrain with 'tissue_hires_image.png' which is the same input for STUtility. However, I can't get segmented by wholebrain. Could I ask if you have done some preprocessing to these images from spacerranger or is there something wrong with my images?

Thanks a lot!

![tissue_lowres_image](https://user-images.githubusercontent.com/8258430/105783852-7794f400-5fb2-11eb-9af1-72109bc8a959.png)

**Comment by ludvigla** [comment]
Hi Cheng,

I could give you some advice on how this could be done. Here’s how I would do it:

1. Downscale image to approximately 4000x4000 pixels
2. Adjust orientation of the mouse brain in a vertical orientation (for this image rotate 90 deg clockwise)
3. Remove background: Use some image editor (e.g.) PhotoShop to remove everything outside the tissue border and replace with white.
4. Convert to grayscale and invert colors. This should make the background black and the nuclei white.

When this is done, your HE image might look something like this:


Then if you export this image (TIF format should work fine), you can use this as inout for the wholebrain workflow.

I hope this helps!

Cheers,
Ludvig

**Comment by quanc1989** [comment]
Thank you for detailed explanation. 

I am still struggling with wholebrain. 
Sometimes I get blank registration. Perhaps something is wrong with my segmentation process.

![image](https://user-images.githubusercontent.com/8258430/105932132-5ce07f00-6087-11eb-96a0-fdb743a1b6e0.png)

Thank you again for your time. I will try it by myself.

**Comment by ludvigla** [comment]
Hi again,

Yeah that shouldn’t happen :-/ When adding correspondence points you should always see the segmented image. Did you manage to get it working?

Cheers,
Ludvig

**Comment by quanc1989** [comment]
Yes, after I removed all the points and manully add new points to the contour, the segmetation worked.
Although this method seems not accurate, I found no other solutions.

Thanks a lot for your suggestions!
