### ISSUE TITLE
STUtility on processed Seurat object

### ISSUE THREAD

**Issue by jnmark** [jbergenstrahle/STUtility#8]
Hello, is there a way to run selected modules from the STUtility library on a processed and annotated Seurat object?

When I try doing so, I get a error: Staffli object is missing from Seurat object. Cannot plot without coordinates

I am guessing this means I need to start from scratch with the 'Load Data' section?

**Comment by ludvigla** [comment]
Hi @jnmark

You guess is correct. When you run the `InputFromTable` function an object called `Staffli` is created and stored inside the Seurat object. This is however not supported by the Seurat workflow so it will be missing if you created the object without running `InputFromTable`. It is possible to add a `Staffli` object manually, but I haven't provided any tutorial for how to do that yet. The easiest solution is to just start from scratch with the Load data section.
